backend:
  host: "order-api-mock"   
  port: "8090"        

kafka:
  host: "specmatic-kafka"
  port: "9093"
  topic: "product-queries"

server:
  port: "8080"

management:
  endpoints:
    web:
      exposure:
        include: "*"



